### ISSUE TITLE
Update to new polymer version

### ISSUE THREAD

**Issue by damondouglas** [dart-lang/polymer-dart-patterns#32]
- [x] web/basics/binding_to_a_field/index.html
- [x] web/basics/binding_to_a_complex_object/index.html
- [x] web/basics/binding_to_a_map/index.html
- [x] web/basics/binding_to_a_native_html_element/index.html
- [x] web/basics/binding_to_a_style/index.html
- [x] web/basics/finding_shadow_dom_elements/index.html
- [ ] web/basics/using_bind_to_create_a_single_template_instance/index.html
- [ ] web/basics/creating_a_one_time_binding/index.html
- [ ] web/basics/using_a_computed_property/index.html
- [ ] web/control_flow/conditionally_hiding_an_element/index.html
- [ ] web/control_flow/getting_the_iteration_index_when_looping_over_a_collection/index.html
- [ ] web/control_flow/looping_over_a_collection_using_iterative_templates/index.html
- [ ] web/control_flow/using_conditional_templates/index.html
- [ ] web/control_flow/using_template_repeat_with_a_table_row_or_an_option/index.html
- [ ] web/insertion_points/creating_an_insertion_point_using_the_control_tag/index.html
- [ ] web/insertion_points/creating_insertion_points_using_the_select_attribute/index.html
- [ ] web/insertion_points/accessing_the_dom_inside_a_content_tag/index.html
- [ ] web/insertion_points/retrieving_the_insertion_points_for_distributed_nodes/index.html
- [ ] web/inheritance/extending_a_polymer_element/index.html
- [ ] web/inheritance/overriding_an_inherited_method/index.html
- [ ] web/observing_changes/observing_changes_to_element_fields/index.html
- [ ] web/observing_changes/observing_changes_to_light_dom_children/index.html
- [ ] web/observing_changes/watching_for_changes_to_a_nested_object/index.html
- [ ] web/forms/binding_a_boolean_field_to_a_checkbox/index.html
- [ ] web/forms/binding_to_a_text_input/index.html
- [ ] web/forms/binding_to_a_textarea/index.html
- [ ] web/forms/implementing_simple_autocompletion/index.html
- [ ] web/forms/implementing_simple_validation/index.html
- [ ] web/forms/selecting_one_item_using_radio_buttons/index.html
- [ ] web/forms/selecting_many_items_using_checkboxes/index.html
- [ ] web/events/using_custom_events/index.html
- [ ] web/styling_elements/applying_styles_by_piercing_shadow_dom_boundaries/index.html
- [ ] web/styling_elements/defining_styles_inside_a_polymer_element/index.html
- [ ] web/styling_elements/programmatically_changing_the_styles_of_an_element/index.html
- [ ] web/styling_elements/styling_distributed_nodes/index.html
- [ ] web/styling_elements/using_host_context_to_theme_an_element/index.html
- [ ] web/styling_elements/using_host_with_a_css_selector/index.html
- [ ] web/styling_elements/using_host_with_pseudo_classes/index.html
- [ ] web/layout_attributes/nesting_flex_layouts/index.html
- [ ] web/layout_attributes/using_flex/index.html
- [ ] web/layout_attributes/using_layout_attributes/index.html
- [ ] web/core_elements/core_toolbar/adding_a_menu_button/index.html
- [ ] web/core_elements/core_toolbar/adding_button_rows/index.html
- [ ] web/core_elements/core_toolbar/changing_the_toolbar_size/index.html
- [ ] web/core_elements/core_toolbar/using_core_toolbar/index.html

@jakemac53 , I created this issue to field any questions.
Is there something needed to get `{{}}` responding to property changes?  Getting `{{color}}` to be replaced by `MyElement.color` in [binding_to_a_field](https://github.com/damondouglas/polymer-dart-patterns/blob/polymer-0.17/web/basics/binding_to_a_field) remains a challenge.

Following [sample-todomvc-polymer](https://github.com/dart-lang/sample-todomvc-polymer/tree/polymer-0.17), I started to modify [pubspec.yaml](https://github.com/damondouglas/polymer-dart-patterns/blob/polymer-0.17/pubspec.yaml) and [binding_to_a_field/my_element.dart](https://github.com/damondouglas/polymer-dart-patterns/blob/polymer-0.17/web/basics/binding_to_a_field/my_element.dart).  I created [binding_to_a_field/index.dart](https://github.com/damondouglas/polymer-dart-patterns/blob/polymer-0.17/web/basics/binding_to_a_field/index.dart) temporarily to help troubleshoot.  Later I hope to refactor so there is no need for `index.dart`.

**Comment by jakemac53** [comment]
So the issue here is actually in [my_element.html](https://github.com/damondouglas/polymer-dart-patterns/blob/polymer-0.17/web/basics/binding_to_a_field/my_element.html). The `{{color}}` binding needs to be wrapped in a span. No whitespace or any other characters are allowed next to bindings any more, see the [js migration guide](https://www.polymer-project.org/1.0/docs/migration.html#data-binding).

Also, instead of  hand writing all the smoke config in the index.dart, I would recommend just importing `package:smoke/mirrors.dart`; and then calling `useMirrors()` at the top of your main, instead of `useGeneratedCode`. That should save a lot of time, and is fine just for the examples.

**Comment by damondouglas** [comment]
@jakemac53 Working now \o/.  I'll follow through with the other examples.

**Comment by jakemac53** [comment]
Also fwiw, I did just update the wiki with a translated version of the JS dev guide https://github.com/dart-lang/polymer-dart/wiki

**Comment by damondouglas** [comment]
@jakemac53 Thank you for this! I have been getting weird errors.  This will help.

**Comment by jakemac53** [comment]
@damondouglas Looks like an error trying to access js object `Polymer.Dart`. If you post a gist or something I can try and investigate, it seems that the initializers aren't running in the proper order.

**Comment by jakemac53** [comment]
One idea, are you using initWebComponents or initPolymer?

**Comment by damondouglas** [comment]
@jakemac53 I am using `initPolymer`.  I resolved the error.  I forgot to comment out the entry point in my pubspec.yaml web_component transformer.  This experience made me think to create a troubleshooting checklist in the Polymer Wiki to help others.

```
- web_components:
    entry_points:
    - web/basics/binding_to_a_complex_object/index.html
```

**Comment by dam0vm3nt** [comment]
Hey Jake, Thank for your great help. I need to understand something better.
By reading the wiki it seams that the whole @Observable thing is gone and
one has to col set API and list change mutation API evry time he wants to
change it's model (in mvc sense).
This IMHO is very very bad. Do you think that there will be chances it will
be reintroduced? I hope so because otherwise how can one of two component
sharing a common object be notified of a change to a subproperty made by
the other? This could be a major problem for polymer1.0 to be adopted (for
me at least is blocking).

Il giorno mar 8 set 2015 22:23 Jacob MacDonald <notifications@github.com>
ha scritto:

**Comment by jakemac53** [comment]
@dam0vm3nt this has come up on a few threads, the strategy for the initial release is to just match Polymer JS functionality, which is where this comes from. We will be working on a way to use Observables on top of this system, so you can get the same functionality as before. Please follow up in [this issue](https://github.com/dart-lang/polymer-dart/issues/570)

**Comment by jakemac53** [comment]
@damondouglas I added https://github.com/dart-lang/polymer-dart/issues/571 to help with this as well

**Comment by jakemac53** [comment]
Also @damondouglas if you want me to start reviewing some of these as you go we could make a new branch in the repo? Or if you want to wait and send them all at once that works to, just let me know.

**Comment by damondouglas** [comment]
@jakemac53 That would be great if you don't mind.  I already pushed some progress to [damondouglas/polymer-dart-patterns/tree/polymer-0.17](https://github.com/damondouglas/polymer-dart-patterns/tree/polymer-0.17).

**Comment by jakemac53** [comment]
Ok, I just created a 0.17.0 branch here, mind doing a pull request to that branch? That way its easier to keep track of comments/changes

**Comment by butlermatt** [comment]
I believe some of these examples need to be reviewed again. For instance I noticed the first sample (Basics Binding to a field) is still using the `@observable` field. This is true on both master and 0.17 branch.

**Comment by jakemac53** [comment]
These haven't been fully updated yet, and also still need to be verified etc. Definitely still some work to do.

**Comment by zoechi** [comment]
Felipe doesn't seem to have time. I have planned to continue working on the patterns when I'm done with the polymer_elements demos, but if someone else wants to take a stab, feel free :)

**Comment by damondouglas** [comment]
@jakemac53 @zoechi I finally found a full-time job and jumping back into this.  Thank you for your patience.

**Comment by zoechi** [comment]
Congrats @damondouglas ! 
The port should be completed. 
Checking if everything is still working with the last Polymer version is probably a good idea.

**Comment by jakemac53** [comment]
closing this for now as I think its completed?

**Comment by zoechi** [comment]
I think so as well.
