### ISSUE TITLE
pubspec.yaml needs 'browser' dependency for 'web/basics' snippets?

### ISSUE THREAD

**Issue by lubi888** [dart-lang/polymer-dart-patterns#43]
Hi guys, 

Some of the web/basics e.g.'s wont load unless I add the 'browser' dependency to pubspec.yaml. It's loads the basic index.html and most of the other e.g.'s but definitely a few of the web/browser snippets load all the html code but the page is blank.

Using dart 1.16.0 on linux mint.

Here's the output:

xx@xx ~/dart/polymer/polymer-dart-patterns $ pub serve
Loading source assets... 
Loading polymer transformers... 
Serving polymer_dart_samples web on http://localhost:8080
[web] GET basics/binding_to_a_native_html_element/ → (cached) polymer_dart_samples|web/basics/binding_to_a_native_html_element/index.html
Build completed successfully
[web] GET packages/browser/dart.js → Could not find asset browser|lib/dart.js.
[web] GET Served 3 cached assets.

Suggested pubspec.yaml single line to add:

dependencies:
  polymer: ^1.0.0-rc.12
  polymer_elements: ^1.0.0-rc.5
  web_components: ^0.12.2
 **browser: "^0.10.0+2"**

**Comment by zoechi** [comment]
I this also in Dartium or only in other browsers?
